[project]
name = "llama"
version = "0.1.0"
description = "Package for alignment and reconstruction of laminography data."
dependencies = [
        "ffmpeg-python",
        "h5py",
        "matplotlib",
        "numpy",
        "pandas",
        "psutil",
        "pympler",
        "scipy",
        "scikit-image",
        "statsmodels",
        "vtk",
        "opencv-python"
]
requires-python = ">=3.0"

[tool.setuptools_scm]

[tool.mypy]
plugins = "numpy.typing.mypy_plugin"

[tool.ruff]
line-length = 100
target-version = "py310"

[tool.setuptools.package-data]
"llama" = ["py.typed"]

[tool.setuptools.packages.find]
where = ["src"]
