# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  LAMINO_ALIGN_DATA_DIR: /local/hruth/lamino_ci_test_data
  CONDA_ROOT: /local/hruth/runner-envs/miniconda3/

permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Create environment
      id: create_env
      run: |
        export ENVNAME=ci_py311_$(date +%s)
        conda create -n $ENVNAME python=3.11
        echo "ENVNAME=$ENVNAME" >> $GITHUB_ENV
        conda activate $ENVNAME

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test with pytest
      run: |
        pytest
