# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

# env:
#   LAMINO_ALIGN_DATA_DIR: /local/ci_tests/pyxalign/

permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: setup
        run: |
          source ~/.bashrc
          echo $PYXALIGN_CI_TEST_DATA_DIR
          export CUDA_VISIBLE_DEVICES=1
          ls
          podman images


      - name: Build container
        run: |
          git pull origin development
          podman build Dockerfile
          podman images